name: ci

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout respository
        uses: actions/checkout@v2

      - name: Setup haskell
        uses: haskell/actions/setup@v1
        id: setup-haskell
        with:
          ghc-version: "8.10.7"
          enable-stack: true
          stack-version: "latest"

      - name: Cache stack
        uses: actions/cache@v2
        env:
          cache-name: cache-stack
        with:
          path: ${{ steps.setup-haskell.outputs.stack-root }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: |
          stack test --system-ghc
